apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-a
  template:
    metadata:
      labels:
        app: api-a
    spec:
      containers:
        - name: api-a
          image: api-a:1.0
          ports:
            - containerPort: 8000
          command: ["uvicorn"]
          args: ["app:app", "--host", "0.0.0.0", "--port", "8000"]
---
apiVersion: v1
kind: Service
metadata:
  name: api-a
spec:
  selector:
    app: api-a
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP